version: "3"

services:
  app:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8050:80"
    container_name: app_nginx
    depends_on:
      - php

  php:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
        - mysql
    container_name: app_php

  mysql:
      image: 'mariadb:latest'
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - './tmp/mysql:/var/lib/mysql'
      container_name: app_db



